name: Compilar Sistema Hoteleiro


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Obter o código fonte
      uses: actions/checkout@v4


    - name: Configurar o Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' 

    - name: Compilar o código fonte
      run: |
        mkdir -p bin
        javac src/model/*.java src/repository/*.java src/service/*.java src/view/*.java -d bin

    - name: Verificar estado da compilação
      run: echo "Compilação concluída com absoluto sucesso! O código não tem erros de sintaxe."
